social_oms_integration/force-app/main/default/objects/Order/fields/Channel_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_Type__c</fullName>
    <label>Channel Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

social_oms_integration/force-app/main/default/objects/Reason_Code_Settings__mdt/Reason_Code_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Reason Code Settings</label>
    <pluralLabel>Reason Code Settings</pluralLabel>
</CustomObject>

social_oms_integration/force-app/main/default/objects/Reason_Code_Settings__mdt/fields/Instagram__c.field-meta.xml
<CustomField>
    <fullName>Instagram__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Instagram</label>
    <type>Checkbox</type>
</CustomField>

social_oms_integration/force-app/main/default/objects/Reason_Code_Settings__mdt/fields/TikTok__c.field-meta.xml
<CustomField>
    <fullName>TikTok__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TikTok</label>
    <type>Checkbox</type>
</CustomField>

social_oms_integration/force-app/main/default/classes/OrderTriggerHandler.cls
public with sharing class OrderTriggerHandler {
    public static void handleCancellationReason(List<Order> orderList){
        List<Reason_Code_Settings__mdt> metaList = [SELECT MasterLabel, DeveloperName,TikTok__c, Instagram__c FROM Reason_Code_Settings__mdt];
        if (!metaList[0].Instagram__c) {
            Set<id> ordersId = new Set<id>();
                for (Order order : orderList) {
                    ordersId.add(order.id);
                }

            List<Order> orderSumList = [SELECT ID, Channel_Type__c FROM Order WHERE ID IN: ordersId AND Channel_Type__c = 'Instagram'];
            if (!orderSumList.isEmpty()) {
                HandleReasonCodes.updatePicklistFieldInstagram();
            }
        }
        
    }
}